#!/usr/bin/env python
"""Generate the vector figure panels that do not already exist in analysis/figures/.

Output is PDF rather than PNG: at this point count vector output is both smaller and
sharper than a 180 dpi raster.  ``nb_lib.plots.savefig`` is hard-coded to PNG, so the
style and colour constants are reused but the writer is replaced.

Usage:  build_figures.py --out figures/panels
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent))
import paperdata as D  # noqa: E402

sys.path.insert(0, str(D.REPO))
from analysis.nb_lib import plots as P  # noqa: E402

OUT = Path("figures/panels")
BUILDERS: dict[str, callable] = {}


def figure(name: str):
    def deco(fn):
        BUILDERS[name] = fn
        return fn

    return deco


def savepdf(fig, name: str) -> Path:
    out = OUT / f"{name}.pdf"
    out.parent.mkdir(parents=True, exist_ok=True)
    # Suppressing the creation date keeps regenerated bytes identical run to run.
    fig.savefig(out, bbox_inches="tight", metadata={"CreationDate": None})
    plt.close(fig)
    return out


def style():
    P.style()
    plt.rcParams.update(
        {
            "pdf.fonttype": 42,
            "font.family": "serif",
            "font.serif": ["Nimbus Roman", "Times New Roman", "DejaVu Serif"],
            "font.size": 8.5,
            "axes.titlesize": 9,
            "axes.labelsize": 8.5,
            "legend.fontsize": 7.5,
            "xtick.labelsize": 7.5,
            "ytick.labelsize": 7.5,
        }
    )


# --------------------------------------------------------------------------- #
@figure("fig_coverage_matrix")
def _():
    v = D.view()
    fig, axes = plt.subplots(
        len(D.BENCHMARKS), len(D.TOPO_ORDER), figsize=(9.0, 8.4), sharex=True, sharey=True
    )
    vmax = 0
    grids = {}
    for bi, b in enumerate(D.BENCHMARKS):
        for ti, t in enumerate(D.TOPO_ORDER):
            sub = v[(v.benchmark == b) & (v.topology == t)]
            g = np.zeros((len(D.SIZE_ORDER), len(D.REAS_ORDER)))
            for si, s in enumerate(D.SIZE_ORDER):
                for ri, r in enumerate(D.REAS_ORDER):
                    g[si, ri] = len(sub[(sub.model_size == s) & (sub.reasoning_level == r)])
            grids[(b, t)] = g
            vmax = max(vmax, g.max())
    for bi, b in enumerate(D.BENCHMARKS):
        for ti, t in enumerate(D.TOPO_ORDER):
            ax = axes[bi, ti]
            g = grids[(b, t)]
            ax.imshow(g, cmap="Blues", vmin=0, vmax=vmax, aspect="auto")
            for si in range(g.shape[0]):
                for ri in range(g.shape[1]):
                    n = int(g[si, ri])
                    ax.text(
                        ri, si, str(n), ha="center", va="center", fontsize=6,
                        color="white" if n > 0.6 * vmax else "#334155",
                    )
            if bi == 0:
                ax.set_title(D.TOPO_LABEL[t])
            if ti == 0:
                ax.set_ylabel(f"{D.BENCH_LABEL[b]}\nmodel size")
                ax.set_yticks(range(len(D.SIZE_ORDER)), D.SIZE_ORDER)
            if bi == len(D.BENCHMARKS) - 1:
                ax.set_xticks(range(len(D.REAS_ORDER)), D.REAS_ORDER, rotation=45, ha="right")
            ax.grid(False)
    fig.suptitle("Seed-level cells per design point (post-trim core view)", y=0.995)
    fig.tight_layout()
    savepdf(fig, "fig_coverage_matrix")


@figure("fig_stratum_caterpillar")
def _():
    s = D.csv("axis_relationships/axis_stratified_contrasts.csv")
    s = s[s.metric == "accuracy"].copy()
    pooled = D.csv("axis_relationships/axis_matched_contrasts.csv")
    pooled = pooled[pooled.metric == "accuracy"]
    fig, axes = plt.subplots(2, 3, figsize=(9.2, 5.4))
    contrasts = sorted(s.contrast.unique())
    for ax, cname in zip(axes.ravel(), contrasts):
        sub = s[s.contrast == cname].sort_values("delta").reset_index(drop=True)
        x = np.arange(len(sub))
        ax.vlines(x, sub.ci_low, sub.ci_high, color="#cbd5e1", lw=0.7)
        colors = [
            P.BENCH_COLORS.get(b, P.PRIMARY) for b in sub.benchmark
        ]
        ax.scatter(x, sub.delta, s=5, c=colors, zorder=3)
        ax.axhline(0, color="0.4", lw=0.8, ls="--")
        pv = pooled[pooled.contrast == cname].delta.mean()
        if np.isfinite(pv):
            ax.axhline(pv, color="#dc2626", lw=1.0)
        ax.set_title(cname.replace("_", " "), fontsize=8)
        ax.set_xlabel("stratum (sorted)")
        ax.set_ylabel(r"$\Delta$ accuracy")
        frac = ((sub.ci_low > 0) | (sub.ci_high < 0)).mean()
        ax.text(
            0.02, 0.95, f"$k$={len(sub)}, {100 * frac:.0f}% excl. 0",
            transform=ax.transAxes, va="top", fontsize=6.5, color="#334155",
        )
    for ax in axes.ravel()[len(contrasts):]:
        ax.axis("off")
    handles = [
        plt.Line2D([], [], marker="o", ls="", color=P.BENCH_COLORS[b], label=D.BENCH_LABEL[b], ms=4)
        for b in D.BENCHMARKS
    ]
    handles.append(plt.Line2D([], [], color="#dc2626", label="pooled matched contrast"))
    fig.legend(handles=handles, loc="lower center", ncol=5, frameon=False, bbox_to_anchor=(0.5, -0.03))
    fig.suptitle("Every stratified accuracy contrast, sorted within contrast", y=1.0)
    fig.tight_layout()
    savepdf(fig, "fig_stratum_caterpillar")


@figure("fig_contrast_forest")
def _():
    c = D.csv("axis_relationships/axis_matched_contrasts.csv")
    c = c[c.metric == "accuracy"].copy()
    fig, axes = plt.subplots(1, 4, figsize=(9.4, 6.6), sharey=True)
    axrank = {a: i for i, a in enumerate(D.AXIS_LABEL)}
    order = (
        c[["axis", "contrast"]]
        .drop_duplicates()
        .assign(k=lambda d: d.axis.map(lambda a: axrank.get(a, 9)))
        .sort_values(["k", "contrast"])
        .contrast.tolist()
    )
    ypos = {n: i for i, n in enumerate(order[::-1])}
    for ax, b in zip(axes, D.BENCHMARKS):
        sub = c[c.benchmark == b]
        y = [ypos[n] for n in sub.contrast]
        ax.hlines(y, sub.ci_low, sub.ci_high, color=P.BENCH_COLORS[b], lw=1.2)
        ax.plot(sub.delta, y, "o", color=P.BENCH_COLORS[b], ms=3.2)
        ax.axvline(0, color="0.5", lw=0.8, ls="--")
        ax.set_title(D.BENCH_LABEL[b])
        ax.set_xlabel(r"$\Delta$ accuracy")
    axes[0].set_yticks(range(len(order)), [n.replace("_", " ") for n in order[::-1]])
    fig.suptitle("All matched adjacent-level accuracy contrasts", y=1.0)
    fig.tight_layout()
    savepdf(fig, "fig_contrast_forest")


@figure("fig_round_dynamics_size")
def _():
    ag = D.agents(["topology", "model_size", "round", "correct"])
    ag = ag[ag.topology.isin(["decentralized", "centralized"])]
    g = (
        ag.groupby(["topology", "model_size", "round"], observed=True)
        .correct.mean()
        .reset_index()
    )
    fig, axes = plt.subplots(1, 2, figsize=(7.4, 3.1), sharey=True)
    xs = np.arange(len(D.SIZE_ORDER))
    for ax, t in zip(axes, ["decentralized", "centralized"]):
        sub = g[g.topology == t]
        for r, ls in [(0, "--"), (1, "-")]:
            ys = [
                sub[(sub.model_size == s) & (sub["round"] == r)].correct.mean()
                for s in D.SIZE_ORDER
            ]
            ax.plot(xs, ys, ls, marker="o", ms=3.5, color=P.TOPO_COLORS[t], label=f"round {r}")
        ax.set_xticks(xs, D.SIZE_ORDER)
        ax.set_xlabel("model size")
        ax.set_title(D.TOPO_LABEL[t])
        ax.legend(frameon=False)
    axes[0].set_ylabel("per-agent accuracy")
    fig.suptitle("Round-over-round per-agent accuracy by capacity", y=1.02)
    fig.tight_layout()
    savepdf(fig, "fig_round_dynamics_size")


@figure("fig_equivalence_arrows")
def _():
    grid = D.csv("scaling_equivalence/size_reasoning_grid.csv")
    pairs = D.csv("scaling_equivalence/nearest_equivalence_pairs.csv")
    grid = grid[grid.scope == "all_systems"]
    pairs = pairs[pairs.scope == "all_systems"]
    fig, axes = plt.subplots(2, 2, figsize=(8.6, 6.4))
    for ax, b in zip(axes.ravel(), D.BENCHMARKS):
        g = grid[grid.benchmark == b]
        for ri, r in enumerate(D.REAS_ORDER):
            gg = g[g.reasoning_level == r].sort_values("cost")
            ax.plot(
                gg.cost, gg.accuracy, marker="o", ms=3.2, lw=1.0,
                color=P.REAS_COLORS.get(r, P.PRIMARY), label=r if b == "gpqa" else None,
            )
        pp = pairs[pairs.benchmark == b]
        tgt = {(r.model_size, r.reasoning_level): (r.cost, r.accuracy) for r in g.itertuples()}
        for r in pp.itertuples():
            a = tgt.get((r.target_model_size, r.target_reasoning))
            c = tgt.get((r.candidate_model_size, r.candidate_reasoning))
            if a and c:
                ax.annotate(
                    "", xy=c, xytext=a,
                    arrowprops=dict(arrowstyle="->", color="#94a3b8", lw=0.6, alpha=0.75),
                )
        ax.set_xscale("log")
        ax.set_xlabel("cost proxy (params $\\times$ tokens)")
        ax.set_ylabel("accuracy")
        ax.set_title(D.BENCH_LABEL[b])
    axes[0, 0].legend(frameon=False, title="reasoning", fontsize=6.5, title_fontsize=7)
    fig.suptitle(
        "Cost-accuracy surface with arrows from each low-reasoning target to its "
        "nearest cheaper equivalent",
        y=1.0,
    )
    fig.tight_layout()
    savepdf(fig, "fig_equivalence_arrows")


@figure("fig_size_reasoning_heatmap")
def _():
    v = D.view()
    fig, axes = plt.subplots(1, 4, figsize=(9.6, 2.9))
    for ax, b in zip(axes, D.BENCHMARKS):
        sub = v[v.benchmark == b]
        g = np.full((len(D.SIZE_ORDER), len(D.REAS_ORDER)), np.nan)
        capped = np.zeros_like(g, dtype=bool)
        for si, s in enumerate(D.SIZE_ORDER):
            for ri, r in enumerate(D.REAS_ORDER):
                cell = sub[(sub.model_size == s) & (sub.reasoning_level == r)]
                if len(cell):
                    g[si, ri] = cell.accuracy.mean()
                    capped[si, ri] = bool(cell.ctx32b_capped.any())
        im = ax.imshow(g, cmap="viridis", aspect="auto", vmin=0.2, vmax=0.9)
        for si in range(g.shape[0]):
            for ri in range(g.shape[1]):
                if np.isnan(g[si, ri]):
                    continue
                ax.text(
                    ri, si, f"{g[si, ri]:.2f}", ha="center", va="center", fontsize=6,
                    color="white" if g[si, ri] < 0.62 else "black",
                )
                if capped[si, ri]:
                    ax.add_patch(
                        plt.Rectangle(
                            (ri - 0.5, si - 0.5), 1, 1, fill=False, hatch="///",
                            edgecolor="#dc2626", lw=0.8,
                        )
                    )
        ax.set_xticks(range(len(D.REAS_ORDER)), D.REAS_ORDER, rotation=45, ha="right")
        ax.set_yticks(range(len(D.SIZE_ORDER)), D.SIZE_ORDER)
        ax.set_title(D.BENCH_LABEL[b])
        ax.grid(False)
    fig.colorbar(im, ax=axes, shrink=0.85, label="accuracy", pad=0.015)
    fig.suptitle(
        "Capacity $\\times$ reasoning accuracy; red hatching marks context-capped 32B cells",
        y=1.04,
    )
    savepdf(fig, "fig_size_reasoning_heatmap")


@figure("fig_metric_correlation")
def _():
    v = D.view()
    cols = [
        "accuracy", "error_rate", "pa_ece_prim", "pa_ece_db", "pa_ece_plugin15",
        "pa_signed_gap", "pa_brier", "pa_brier_rel", "pa_cox_slope",
        "vote_ece_prim", "vote_signed_gap", "vote_brier", "vote_brier_rel",
        "fp_ece_prim", "fp_signed_gap", "fp_brier",
        "delta_vote_prim", "delta_fp_prim",
        "mean_reasoning_tokens", "mean_total_tokens", "mean_turns", "mean_messages",
        "cost", "Ec", "Ae", "Opct", "log2_params", "reas_rank",
    ]
    cols = [c for c in cols if c in v.columns]
    m = v[cols].corr(method="spearman")
    fig, ax = plt.subplots(figsize=(7.6, 6.8))
    im = ax.imshow(m, cmap="RdBu_r", vmin=-1, vmax=1)
    ax.set_xticks(range(len(cols)), [c.replace("_", " ") for c in cols], rotation=90)
    ax.set_yticks(range(len(cols)), [c.replace("_", " ") for c in cols])
    ax.grid(False)
    fig.colorbar(im, ax=ax, shrink=0.8, label="Spearman $\\rho$")
    ax.set_title("Rank correlation among cell-level outcome columns")
    fig.tight_layout()
    savepdf(fig, "fig_metric_correlation")


@figure("fig_seed_funnel")
def _():
    v = D.view()
    g = v.groupby("design_cell", observed=True).agg(
        k=("accuracy", "size"), sd=("accuracy", "std"),
        acc=("accuracy", "mean"), n=("n_questions", "mean"),
        bench=("benchmark", "first"),
    )
    g = g[g.k >= 2].dropna(subset=["sd"])
    fig, ax = plt.subplots(figsize=(6.4, 3.6))
    for b in D.BENCHMARKS:
        sub = g[g.bench == b]
        ax.scatter(sub.acc, sub.sd, s=5, alpha=0.5, color=P.BENCH_COLORS[b], label=D.BENCH_LABEL[b])
    p = np.linspace(0.02, 0.98, 200)
    ax.plot(p, np.sqrt(p * (1 - p) / 200.0), color="0.25", lw=1.2, label="binomial, $n=200$")
    ax.set_xlabel("design-cell mean accuracy")
    ax.set_ylabel("across-seed SD of accuracy")
    ax.legend(frameon=False, ncol=2, fontsize=6.5)
    ax.set_title("Seed dispersion against the question-sampling expectation")
    fig.tight_layout()
    savepdf(fig, "fig_seed_funnel")


@figure("fig_delta_by_bench_topo")
def _():
    v = D.view()
    mcq = v[v.benchmark.isin(D.MCQ)]
    fig, axes = plt.subplots(1, 2, figsize=(8.4, 3.4), sharey=False)
    for ax, (col, title) in zip(
        axes,
        [("delta_vote_prim", r"$\Delta$ECE, vote fraction"),
         ("delta_fp_prim", r"$\Delta$ECE, final producer")],
    ):
        width = 0.2
        for ti, t in enumerate([x for x in D.TOPO_ORDER if x != "single_agent"]):
            xs, ys, es = [], [], []
            for bi, b in enumerate(D.MCQ):
                sub = mcq[(mcq.benchmark == b) & (mcq.topology == t)][col].dropna()
                if not len(sub):
                    continue
                xs.append(bi + (ti - 1) * width)
                ys.append(sub.mean())
                es.append(sub.std() / np.sqrt(len(sub)))
            ax.bar(xs, ys, width=width * 0.92, yerr=es, capsize=2,
                   color=P.TOPO_COLORS[t], label=D.TOPO_LABEL[t])
        ax.axhline(0, color="0.4", lw=0.8)
        ax.set_xticks(range(len(D.MCQ)), [D.BENCH_LABEL[b] for b in D.MCQ])
        ax.set_title(title)
        ax.set_ylabel(r"$\Delta$ECE")
    axes[0].legend(frameon=False, fontsize=7)
    fig.suptitle("Coordination calibration penalty by benchmark and topology", y=1.02)
    fig.tight_layout()
    savepdf(fig, "fig_delta_by_bench_topo")


@figure("fig_scaling_coefficients")
def _():
    c = D.csv("scaling_equivalence/scaling_law_coefficients.csv")
    c = c[c.scope == "core_all_cap_control"]
    fig, axes = plt.subplots(1, 2, figsize=(8.2, 3.4), sharey=True)
    groups = ["all_systems", "topology:single_agent", "topology:independent",
              "topology:decentralized", "topology:centralized"]
    ypos = {g: i for i, g in enumerate(groups[::-1])}
    for ax, (col, se, lab) in zip(
        axes,
        [("coef_log2_params", "se_log2_params", r"$\beta_P$ per parameter doubling"),
         ("coef_log2_reasoning_tokens", "se_log2_reasoning_tokens",
          r"$\beta_R$ per reasoning-token doubling")],
    ):
        for b in D.BENCHMARKS:
            sub = c[c.benchmark == b]
            y = [ypos[g] + (D.BENCHMARKS.index(b) - 1.5) * 0.14 for g in sub.fit_group]
            ax.errorbar(
                sub[col], y, xerr=1.96 * sub[se], fmt="o", ms=3.2, lw=1.0,
                color=P.BENCH_COLORS[b], label=D.BENCH_LABEL[b] if col.endswith("params") else None,
            )
        ax.axvline(0, color="0.5", lw=0.8, ls="--")
        ax.set_xlabel("logit coefficient")
        ax.set_title(lab)
    axes[0].set_yticks(
        range(len(groups)), [g.replace("topology:", "").replace("_", " ") for g in groups[::-1]]
    )
    axes[0].legend(frameon=False, fontsize=6.5)
    fig.suptitle("Capacity and reasoning coefficients by fit group", y=1.02)
    fig.tight_layout()
    savepdf(fig, "fig_scaling_coefficients")


@figure("fig_ece_vs_accuracy")
def _():
    v = D.view()
    mcq = v[v.benchmark.isin(D.MCQ)]
    fig, axes = plt.subplots(1, 3, figsize=(9.2, 3.1), sharex=True, sharey=True)
    for ax, (col, title) in zip(
        axes,
        [("pa_ece_prim", "per-agent ECE"), ("vote_ece_prim", "vote ECE"),
         ("fp_ece_prim", "final-producer ECE")],
    ):
        for s in D.SIZE_ORDER:
            mk = P.SIZE_MARKERS[s]
            sub = mcq[mcq.model_size == s]
            ax.scatter(sub.accuracy, sub[col], s=6, marker=mk, alpha=0.55, label=s)
        ax.set_xlabel("cell accuracy")
        ax.set_title(title)
    axes[0].set_ylabel("ECE")
    axes[0].legend(frameon=False, ncol=2, fontsize=6, title="size", title_fontsize=6.5)
    fig.suptitle("Calibration against accuracy, by capacity (MCQ cells)", y=1.02)
    fig.tight_layout()
    savepdf(fig, "fig_ece_vs_accuracy")


@figure("fig_token_dose")
def _():
    v = D.view()
    fig, axes = plt.subplots(1, 4, figsize=(9.6, 2.9), sharey=False)
    for ax, b in zip(axes, D.BENCHMARKS):
        sub = v[v.benchmark == b]
        for s in D.SIZE_ORDER:
            mk = P.SIZE_MARKERS[s]
            ss = sub[sub.model_size == s]
            ax.scatter(ss.mean_reasoning_tokens, ss.accuracy, s=5, marker=mk, alpha=0.5, label=s)
        ax.set_xscale("symlog", linthresh=100)
        ax.set_xlabel("mean reasoning tokens")
        ax.set_title(D.BENCH_LABEL[b])
    axes[0].set_ylabel("accuracy")
    axes[0].legend(frameon=False, ncol=2, fontsize=6, title="size", title_fontsize=6.5)
    fig.suptitle("Accuracy against realized reasoning dose", y=1.03)
    fig.tight_layout()
    savepdf(fig, "fig_token_dose")


@figure("fig_efficiency")
def _():
    v = D.view()
    mas = v[v.is_mas.astype(bool)]
    fig, axes = plt.subplots(1, 3, figsize=(9.2, 3.0))
    for ax, (col, lab, ref) in zip(
        axes,
        [("Ec", r"coordination efficiency $E_c$", None),
         ("Ae", r"error amplification $A_e$", 1.0),
         ("Opct", r"turn overhead $O\%$", 0.0)],
    ):
        xs = np.arange(len(D.SIZE_ORDER))
        for t in [x for x in D.TOPO_ORDER if x != "single_agent"]:
            ys = [mas[(mas.model_size == s) & (mas.topology == t)][col].mean() for s in D.SIZE_ORDER]
            ax.plot(xs, ys, marker="o", ms=3.5, color=P.TOPO_COLORS[t], label=D.TOPO_LABEL[t])
        if ref is not None:
            ax.axhline(ref, color="0.5", lw=0.8, ls="--")
        ax.set_xticks(xs, D.SIZE_ORDER)
        ax.set_xlabel("model size")
        ax.set_title(lab)
    axes[0].legend(frameon=False, fontsize=6.5)
    fig.suptitle("Coordination efficiency metrics against capacity", y=1.03)
    fig.tight_layout()
    savepdf(fig, "fig_efficiency")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="figures/panels")
    ap.add_argument("--only", default="*")
    args = ap.parse_args()

    global OUT
    OUT = Path(args.out)
    OUT.mkdir(parents=True, exist_ok=True)
    style()

    from fnmatch import fnmatch

    names = [n for n in BUILDERS if fnmatch(n, args.only)]
    for n in sorted(names):
        BUILDERS[n]()
    total = sum(p.stat().st_size for p in OUT.glob("*.pdf"))
    print(f"wrote {len(names)} figure panels to {OUT} ({total / 1e6:.2f} MB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
