#!/usr/bin/env python
"""Summarize the ExperimentCell grid generated by a sweep config."""

from __future__ import annotations

import argparse
from collections import Counter

from agents_scaling.experiment.sweep import load_sweep


def _print_counts(title: str, counts: Counter) -> None:
    print(f"\n{title}")
    for key, value in sorted(counts.items(), key=lambda kv: str(kv[0])):
        print(f"  {key}: {value}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default="configs/full_sweep.yaml")
    args = parser.parse_args()

    cells = load_sweep(args.config)
    if not cells:
        raise SystemExit(f"no cells generated from {args.config!r}")

    print(f"config: {args.config}")
    print(f"cells: {len(cells)}")

    _print_counts("by model_size", Counter(c.model_size for c in cells))
    _print_counts("by topology", Counter(c.topology.value for c in cells))
    _print_counts("by n_agents", Counter(c.n_agents for c in cells))
    _print_counts("by context_share_level", Counter(c.context_share_level.value for c in cells))
    _print_counts("by prompt_complexity_level", Counter(c.prompt_complexity_level for c in cells))
    _print_counts("by reasoning_level", Counter(c.reasoning_level.value for c in cells))
    _print_counts("by benchmark", Counter(c.benchmark for c in cells))
    _print_counts("by seed", Counter(c.seed for c in cells))

    print("\nfirst 5 cell ids")
    for cell in cells[:5]:
        print(f"  {cell.cell_id}")


if __name__ == "__main__":
    main()
